apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: clusterrolebinding2
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: controller-serviceaccount
    namespace: default
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: controller-serviceaccount
  namespace: default
